var al_obj = [
  "",
  "- set appropriate personal and academic goals",
  "- self-reflect using higher order thinking skills",
  "- self-assess short-term and long-term goals",
  "- sets new goals based on evaluation of previous reflection of goals",
  "- self-evaluates on term projects (i.e. note-taking, research, products)",
  "- demonstrate awareness of role within the class community",
  "- contribute actively to the school community",
  "- develop a new mentoring role within the class and community",
  "- demonstrate leadership skills (incl. communicating clearly and assertively, motivating others, etc.) within the class and school community",
  "- communicates effectively with various levels of school community (i.e. teachers, support staff, administration and other students)",
  "- develop and sustain an effective support network with peers",
  "- plan and organize project time lines more effectively and prioritize other assignments appropriately",
  "- prioritize school work and home responsibilities to improve time management",
  "- plan and manage time more effectively at home and at school, including extracurricular activities",
  "- develop organizational and time management skills (executive functioning)",
  "- communicate assignments to parents, ongoing",
  "- prioritize work and responsibilities through use of schedules effectively",
  "- negotiate assignment parameters and due dates",
  "- organize personal and work spaces",
  "- develop a repertoire of organizational and time management skills",
  "- use agenda and calendars effectively in order to keep track of project due dates",
  "- participate actively in class and group discussions (i.e. communication and product completion)",
  "- develop effective leadership skills in group work (i.e. listening and considering all members ideas)",
  "- develop group work skills (self-regulate, cooperation, active listening, equal discussion opportunities)",
  "- self-regulate active learning by identifying on-task and offtask behaviours",
  "- self-regulate (pre-performance)",
  "- self-regulate, emotional response to problems (academic or social)"
];
var num_obj = [
  "",
  "- set appropriate numeracy goals and self-assesses",
  "- VLN - follows and supplements the curriculum",
  "- set a math extension goal (i.e. literacy, presentation)",
  "- demonstrate mastery (90% or higher) on math reviews, study sheets, and tests for each chapter",
  "- organize math work logically and clearly facilitate review",
  "- build a personal bank of strategies to choose from and develop math skills that can be applied in everyday life",
  "- develop review skills for test writing",
  "- work with a peer group to better support learning objectives",
  "- build math vocabulary",
  "- improve clarity and level of elaboration when problem solving",
  "- use a variety of approaches to solve work problems",
  "- decode a work problem and develop a plan to solve",
  "- improve mental maths skills, accuracy and speed through Spirit of Math drills",
  "- explore advanced math topics or math topics of interest",
  "- participate in math contests"
];
var lit_obj = [
  "",
  "- develop basics in grammar, spelling and word choice",
  "- develop good paragraphing techniques (logical organization, non-repetition of ideas, structure, etc.)",
  "- develop full written arguments supported with evidence",
  "- develop effective topic sentences",
  "- develop effective introduction and conclusion paragraphs",
  "- develop pre-writing planning/outlining",
  "- explore a particular writing genre (i.e. letters, reports and short stories)",
  "- transfer content from grammar lessons to own writing",
  "- develop keyboarding skills by increasing w.p.m",
  "- develop cursive writing skills",
  "- edit for grammar and spelling",
  "- edit for content, organization and complexity",
  "- establish broader connections with literature (i.e. poetry, short stories, novels and non-fiction)",
  "- read western classics in order to build vocabulary and writing skills",
  "- broaden knowledge of literary elements (foreshadowing, plot development, etc.)",
  "- develop HOTS (i.e. comparing and evaluating various short stories)",
  "- develop oral fluency skills (breathing, pacing, using pauses for effect)",
  "- elaborate ideas in complete sentences in oral and written communications",
  "- develop full oral arguments supported with evidence",
  "- develop an accurate and sophisticated use of diction",
  "- transfer content from grammar lessons to own writing",
  "- build confidence in French oral communications",
  "- develop fluency in French oral communications",
  "- acquire more French vocabulary and expressions, and develop French oral fluency (i.e. to better communicate with French penpals)",
  "- establish broader connections with French literature from a variety of francophone countries",
  "- develop an appreciation for the French and French- Canadian language and culture",
  "- explore a language independently",
  "- increase digital literacy (navigating internet, sending email, submitting online projects, etc.)",
  "- effective and efficient use of online time ",
  "- use formal language when communicating digitally with peers and other adults",
  "- healthy use of technology"
];
var pbl_obj = [
  "",
  "- set realistic goals for project completion",
  "- able to set some realistic goals independently without teacher/parent guidance",
  "- identify and articulate areas of passion",
  "- plan, research and produce long term projects",
  "- develop time management skills by using agenda and project criteria to plan effectively",
  "- negotiate assignment deadlines",
  "- using HOTS, build connections between notes and focus questions, and product development",
  "- deepen thinking while researching",
  "- develop and apply a criteria set to assess",
  "- identify and amplify areas of passion and develop critical or focus questions",
  "- identify and effectively apply the HOTS : analysis, evaluation and creation",
  "- applies basic note-taking strategies effectively and understands the importance of note-taking in the research process",
  "- able to evaluate appropriate primary and secondary sources",
  "- build connections with and reflect on research notes",
  "- develop a repertoire of research skills including a personal system of notetaking",
  "- utilizing appropriate primary and secondary sources",
  "- develop a repertoire of research skills, including note-taking and accessing, evaluating and filtering a broad variety of sources including evidence of thinking",
  "- able to compile sources into a works cited page",
  "- analyzes notes to make new ideas and synthesizes them to create project elements",
  "- determine appropriate and effective media (visual, oral or written) for presentation",
  "- explores new types of products and tries new approaches to project work",
  "- self-evaluates products mid and post project in order to improve subsequent products",
  "- incorporate more effective strategies to engage the audience in oral presentations",
  "- develop presentation skills with a focus on innovating, captivating and insightful products",
  "- able to articulate ideas understandable to a wide range of audience members",
  "- uses appropriate volume and projection in group presentations",
  "- body language: awareness of eye contact, gestures and emphatic utterances in presentation",
  "- a polite, respectful and engaged audience member"
];

//Declare student strategies
var al_sS = [
  "",
  "- monitor desk, agenda and binder organization",
  "- refer regularly to reflections and goal reflections",
  "- use criteria and evidence for self assessment",
  "- refer regularly to reflections/debriefs and goal reflections",
  "- participate on a school team, in Student Council, join or create a club",
  "- participate actively in service for the school (i.e. volunteering)",
  "- explore other potential roles in the class and school community",
  "- explore potential roles in the class and school community (i.e. leadership)",
  "- uses respectful language when communicating with peers and other community members",
  "- maintaining a positive attitude when working with all class members",
  "- explore graphic organizers for planning and specialize the usage of the agenda for project work",
  "- develop effective and healthy study routines",
  "- refer to goals, criteria and reflections to prioritize",
  "- self-assess effectiveness of planning and deadlines",
  "- monitor and adapt desk, agenda and binder organization",
  "- communicating with parents and teachers regarding school and other activities",
  "- transfer skills and systems to home",
  "- check-in with the teacher and/or parent regularly to help monitor agenda use",
  "- use a to-do list and prioritize items, and use planning binder to set short term goals",
  "- monitor, self-assess and adjust communications in group interactions",
  "- use strategies in discussion, such as using examples/counter-examples, giving a reason, asking for clarification, agreeing/disagreeing, and offering a definition",
  "- set goals for group work then selfassess (i.e. cooperation, effective communication, endeavour to inspire others, provide constructive feedback to others, be sensitive to others, etc.)",
  "- look for cues from teacher to selfregulate behaviour",
  "- using an appropriate level of assertiveness when communicating in a group",
  "- sets goals using strategies to increase on-task behaviours (seating choice, lists, timers)",
  "- use deep breathing and visualize the performance, oral speaking or test going well beforehand",
  "- practice writing tests/contests and oral speaking often",
  "- use a journal before writing tests, contests, and delivering speeches",
  "- utilize strategies to problem solve"
];
var num_sS = [
  "",
  "- set term goals",
  "- self-assess, reflect then adjust study approach appropriately",
  "- VLN - submit year plan for curriculum and challenge",
  "- develop a plan to extend math learning",
  "- access teacher, parent and peer support for content questions",
  "- set goals, self-assess, reflect then adjust study approach appropriately",
  "- access teacher, parent and peer support for content questions",
  "- participate actively in enrichment activities (including curious math, chapter tasks and math games)",
  "- self-monitor strategy choices and applications (skills)",
  "- show work when appropriate",
  "- create a working reference book for math strategies/vocabulary",
  "- identify and work with a peer group",
  "- maintain a math work book, clearly labelled and dated, showing work",
  "- self-monitor clarity (labelling, addressing the question directly, using data provided, etc.) and vocabulary usage in written math explanations",
  "- access teacher, parent and peer support for strategies, feedback and practice",
  "- memorize basic math facts with flash cards and customized times tables",
  "- practice drills regularly (timed or not)",
  "- participate actively in Sprit of Math",
  "- set goals, self-assess, reflect for Spirit of Math drills",
  "- participate actively in enrichment opportunities, such as (a) pursuing an independent study in math (b)	studies in historical mathematics and literature",
  "- participate in a variety of math contests"
];
var lit_sS = [
  "",
  "- self-evaluate using a rubric",
  "- use graphic organizers before writing",
  "- refer to criteria before, during and after writing",
  "- follow writing genre format for a variety of objectives",
  "- use graphic organizers to generate ideas for writing",
  "- revise written work for a chosen objective",
  "- participate actively in grammar lessons (i.e. checking in with the teacher regularly)",
  "- make a goal for writing, assess upon completion",
  "- use COPS to edit",
  "- build vocabulary by using a thesaurus, and creating a personal word bank ",
  "- practice handwriting by using a workbook ",
  "- improve keyboarding skills with a typing tutor (ATRT) and by typing major writing assignments",
  "- utilize in-class program",
  "- Set a reading goal each term to read regularly including western classics and a variety of genre at or above grade level",
  "- read short stories of same genre and compare",
  "- explore a variety of genres outside of the students regular interest",
  "- identify the use of a variety of literary elements when reading",
  "- practice before speaking publicly (i.e. recording, practice at home, with peers)",
  "- initiate and make the most of public speaking opportunities (i.e. morning announcements)",
  "- self-monitor oral communications for completeness and appropriateness",
  "- revise work for purpose of elaboration",
  "- participate in class discussions and debates",
  "- provide thoughtful, constructive feedback",
  "- maximize opportunities by speaking French as much as possible",
  "- use strategies like describing things you don't know in French or using gestures rather than speaking English",
  "- seek opportunities to practice French outside of the classroom (i.e. authentic experiences)",
  "- use POMMES to edit",
  "- use apps, home-study or language learning books",
  "- allocate a percentage of project time to technology, emphasizing use of non digital methods and resources",
  "- set time goals for on-line time",
  "- focus on one task at a time (i.e. not messaging and researching simultaneously)",
  "- edit digital communications before sending",
  "- use appropriate and respectful language online"
];
var pbl_sS = [
  "",
  "- refer to project assessments and goals",
  "- self-monitor and assess product choices",
  "- reflect on past successes, failures, and alternative strategies of presentation",
  "- RAP: identify goals that are relevant, attainable and precise",
  "- use graphic or personal organizers",
  "- access peers and teacher for support, tips and feedback",
  "- weekly check-in with teacher/parent",
  "- use calendars and agenda to plan",
  "- self-monitor higher order thinking skill applications in note-taking and question development",
  "- access peers, teachers & parents and use a journal for brainstorming",
  "- assess topics for appropriateness (resources available, narrow scope)",
  "- participate actively in enrichment opportunities at museums and/or archives",
  "- HOTS will be evident in final projects through evidence of assessment, evaluation and ranking through use of criteria",
  "- creates a HOTS plan of action within the first half of a project",
  "- self-monitor high order thinking skill applications in note-taking",
  "- use graphic organizers and a personal note-taking format to research",
  "- self-monitor note-taking for reflective thinking and content coverage",
  "- self-monitor and assess note-taking",
  "- access appropriate resources using databases, search engines and the Dewey decimal system",
  "- use graphic organizers",
  "- use criteria to determine whether info is note-worthy",
  "- practice and self-monitor sourcing skills, including evaluating sources",
  "- experiment with a variety of note-taking formats",
  "- develop varying research plans for a variety of projects",
  "- refer to criteria to determine validity, reliability, accuracy, authority, timeliness and point of view or bias",
  "- refer to past projects when setting new goals",
  "- choose products based on responses to notes",
  "- create new and diverse products to extend thinking",
  "- self-monitor and assess product choices",
  "- demonstrate completion of projects to teacher when each product is finished",
  "- maintain a journal of product choosing and creating",
  "- apply new skills (non-verbal language, phrasing to lead the audience, reacting to interruptions, waiting for attention) reflect on feedback, and adjust approach",
  "- looks at speaker, asks thoughtful questions/provides constructive feedback",
  "- extends learning by making connections to other students work"
];

//Declare teacher strategies
var al_tS = [
  "",
  "- prompt students to discuss and use new schedules and systems",
  "- model and direct teach goal setting",
  "- direct teach self-assessment using criteria and evidence",
  "- direct teach language of goal setting (i.e. measurable, specific, RAP)",
  "- liaise between staff and student to establish and maintain a community service program",
  "- foster a positive, independent, confident, and goal-oriented attitude in the student",
  "- offer opportunities for school engagement, community and classroom service",
  "- prompt student to use new time management schedules and systems",
  "- promote and model various strategies for prioritizing and schedules, if applicable",
  "- provide due dates and reminders for assignments",
  "- demonstrate a variety of organizational skills and strategies",
  "- prompt student to use new systems and debrief with student after participation opportunities",
  "- monitor communications and dynamics in group interactions",
  "- give student visual or verbal cues to help monitor behaviour",
  "- model and direct teach language and strategies",
  "- direct teach visualizing using the senses, breathing techniques",
  "- prompt student to use new systems and strategies",
  "- provide opportunities to practice",
  "- direct teach emotional regulation",
  "- model strategies to solve problems"
];
var num_tS = [
  "",
  "- review personal plan with student",
  "- provide additional support with content or skills and opportunities for enrichment",
  "- score study sheets and tests and assign a mark for each chapter",
  "- direct teach everyday math (i.e. sports statistics, culinary math)",
  "- provide resources necessary for independent math programs",
  "- direct teach reviewing tests and writing clearly",
  "- direct teach problem solving through different approaches",
  "- provide opportunities for practice",
  "- provide opportunities for skill development",
  "- provide opportunities for math contests"
];
var lit_tS = [
  "",
  "- direct teach writing skills (i.e. developing a thesis statement, establishing logical arguments, exploring organizations of essay development, building connections between ideas, using transitions, avoiding plagiarism, etc.)",
  "- direct teach different writing genres",
  "- provide models of written genres",
  "- provide opportunities to practice writing and reflections",
  "- provide student with grammar resources",
  "- model and encourage good editing practice",
  "- model and direct teach pre-writing strategies",
  "- introduce western classics",
  "- introduce a variety of genre",
  "- direct teach literary elements",
  "- provide examples of different genres of short stories, poetry and novels for the purpose of comparison",
  "- provide opportunities to practice oral communications",
  "- prompt student to complete sentences",
  "- provide vocabulary building resources",
  "- provide opportunities to read and discuss advanced level texts",
  "- provide opportunities to communicate in French and read and discuss advanced level texts in French",
  "- provide student with vocabulary building resources ",
  "- provide resources (short stories, novels, poetry and songs) from a variety of francophone countries",
  "- Direct teach skills and strategies for use of technology",
  "- Direct teach healthy use of technology",
  "- communicate with parents and students regarding online and communication expectations"
];
var pbl_tS = [
  "",
  "- introducing planning strategies (i.e. RAP)",
  "- direct teaching of goal setting",
  "- provide outlines, schedules and graphic organizers",
  "- provide detailed criteria with clear due dates",
  "- model organization and time management strategies/techniques",
  "- provide opportunities to manage varied projects and to practice developing research focus questions",
  "- direct teach note-taking and critical questioning, and explore the relationship between questions and ideas",
  "- provide brainstorming opportunities and strategies or prompts",
  "- direct teach critical questioning",
  "- direct teach historical thinking concepts, including using evidence",
  "- direct teach historical significance and historical perspective in research",
  "- direct teach note-taking and critical questioning, and explore the relationship between questions and ideas",
  "- provide opportunities to manage varied projects, and practice library etiquette and research skills",
  "- direct teach using images in research",
  "- introduce further note-taking formats",
  "- direct teach differentiating between primary and secondary sources",
  "- direct teach evaluating, accessing and determining the importance of primary and secondary sources",
  "- provide opportunities to manage varied projects and to practice dialectical note-taking",
  "- direct teaching note-taking and explore the relationship between ideas and products",
  "- model project process from notetaking and research to product development and self-evaluation",
  "- allows for possibility to redo projects in order to build on skills",
  "- introduce presentation formats",
  "- direct teach relationship between audience, message and medium"
];
